update clusterscan status

diff --git a/charts/inspect/templates/plugins/popeye.yaml b/charts/inspect/templates/plugins/popeye.yaml
--- a/charts/inspect/templates/plugins/popeye.yaml
+++ b/charts/inspect/templates/plugins/popeye.yaml
@@ -18,7 +18,14 @@ spec:
         --all-namespaces \
         --force-exit-zero \
         > $(DONE_DIR)/results.json
-      echo $(DONE_DIR)/results.json > $(DONE_DIR)/done
+      exitcode=$(echo $?)
+      if [ $exitcode -ne 0 ]; then
+        echo "ERROR" > $(DONE_DIR)/error
+        cat /tmp/popeye.log
+      else
+        echo $(DONE_DIR)/results.json > $(DONE_DIR)/done
+      fi
       ls -lh $(DONE_DIR)/
       end=$(date +%s)
-      echo "Scan has finished in $(($end-$start)) seconds"
+      echo "Scan has finished in $(($end-$start)) seconds with exit code $exitcode"
+      exit $exitcode
